### ISSUE TITLE
Replace textures

### ISSUE THREAD

**Issue by vitor251093** [vitor251093/KHDays_FM#7]
All textures need to be replaced with high resolution ones. We already started gattering some textures, but we need to wait until texture replacement is fully implemented in melonDS so this can be done.

https://melonds.kuribo64.net/comments.php?id=182

**Comment by vitor251093** [comment]
By creating a branch based in melonDS's [compute-shader-renderer](https://github.com/melonDS-emu/melonDS/tree/compute-shader-renderer) branch, I've managed to achieve texture replacement. Although, I still can't detect which texture is which so...

![2023-06-16_01-37](https://github.com/vitor251093/KHDays_FM/assets/8976483/6d292bd3-3d62-48f2-976e-a6ec21e30296)

Welcome to texture hell

**Comment by CpazR** [comment]
Honestly, I think some of the texture filtering for characters and environments, while not the best, do a good enough job for the time being.

The menu's are where I'd focused efforts first imo. If nothing else than to make them wide-screen compatible.

**Comment by vitor251093** [comment]
I actually managed to extract some of the textures from the main menu using the other branch, and technically I am even capable of replacing them already.

The current problem is that the extracted images don't look exactly like they should. I can swap them around, like in the print, and they will still be used by the game properly, but if you open them with an image viewer, you will notice them are extremely transparent.

It may be related with RGB conversions, but I haven't checked that possibility yet

**Comment by sandwichwater** [comment]
i think this is probably another windows issue , but i cant seem to build the compute shader branch , very very last step in the compiling process always stops , something to do with ninja failing

**Comment by vitor251093** [comment]
> i think this is probably another windows issue , but i cant seem to build the compute shader branch , very very last step in the compiling process always stops , something to do with ninja failing

Well, the compute shader branch still wasn't merged with the master branch, so it probably has problems that they are still dealing with. I hope the texture replacement system isn't that much affected by later fixes, but in any case, it should be useful to test replacement textures nonetheless.

> though off the top of my head the first thing that comes to mind when you say the textures are transparent is that the same thing happens when you extract the ps2 kh games , the game stacks them for some sort of pseudo antialiasing , though in the ds kh games there is none , so i cant think of any reason why

Interesting. I didn't know about that KH2 fact. Since they reused some assets from KH2 in Days, you may be on to something.

Is there any recommended way to handle KH2 textures when it comes to replacing them?

**Comment by sandwichwater** [comment]
> it probably has problems that they are still dealing with

id think so too , though i can build their compute shader branch just fine without issues , and i can _almost_ build this branch , its just that where normally it would give a success message it gives a failed message

> Is there any recommended way to handle KH2 textures when it comes to replacing them?

what ive always done is decrease the transparency value so i have a fully solid texture , edit it , then change the transparency value back to what it was originally . though oddly enough it only happens for ui and menu textures in the ps2 games , does it happen for all textures here ¿

**Comment by vitor251093** [comment]
> id think so too , though i can build their compute shader branch just fine without issues , and i can almost build this branch , its just that where normally it would give a success message it gives a failed message

Which is the error message exactly?

> what ive always done is decrease the transparency value so i have a fully solid texture , edit it , then change the transparency value back to what it was originally . though oddly enough it only happens for ui and menu textures in the ps2 games , does it happen for all textures here ¿

Yup, at least all the textures from the scene in the screenshot. It may be unrelated to KH2 then...

**Comment by sandwichwater** [comment]
> Which is the error message exactly?

halfway through the final compiling step i get
"FAILED: src/CMakeFiles/core.dir/GPU3D_TexcacheOpenGL.cpp.obj"

then at the very end i get
"ninja: build stopped: subcommand failed."

there are no other error messages but if itll help i can give the full output as well

**Comment by vitor251093** [comment]
The lines between those two may be useful

**Comment by sandwichwater** [comment]
sure :

> FAILED: src/CMakeFiles/core.dir/GPU3D_TexcacheOpenGL.cpp.obj
D:\msys64\mingw64\bin\c++.exe -DARCHITECTURE_x86_64=1 -DJIT_ENABLED -DKHDAYSMM_VERSION=\"0.1.1\" -DO
GLRENDERER_ENABLED -ID:/msys64/home/User/KHDays_FM/src/teakra/src/../include -O3 -DNDEBUG -std=gnu+
+17 -flto=auto -fno-fat-lto-objects -MD -MT src/CMakeFiles/core.dir/GPU3D_TexcacheOpenGL.cpp.obj -MF
 src\CMakeFiles\core.dir\GPU3D_TexcacheOpenGL.cpp.obj.d -o src/CMakeFiles/core.dir/GPU3D_TexcacheOpe
nGL.cpp.obj -c D:/msys64/home/User/KHDays_FM/src/GPU3D_TexcacheOpenGL.cpp
D:/msys64/home/User/KHDays_FM/src/GPU3D_TexcacheOpenGL.cpp: In member function 'void GPU3D::Texcach
eOpenGLLoader::UploadTexture(u32, GLuint, u32, u32, u32, void*)':
D:/msys64/home/User/KHDays_FM/src/GPU3D_TexcacheOpenGL.cpp:30:38: error: cannot convert 'const std:
:filesystem::__cxx11::path::value_type*' {aka 'const wchar_t*'} to 'const char*' in initialization
   30 |     const char* path = fullPath.c_str();
      |                        ~~~~~~~~~~~~~~^~
      |                                      |
      |                                      const std::filesystem::__cxx11::path::value_type* {aka
const wchar_t*}
[55/138] Building CXX object src/CMakeFiles/core.dir/ARMJIT_x64/ARMJIT_Branch.cpp.obj
In file included from D:/msys64/mingw64/lib/gcc/x86_64-w64-mingw32/13.1.0/include/stddef.h:1,
                 from D:/msys64/mingw64/include/stdint.h:32,
                 from D:/msys64/mingw64/lib/gcc/x86_64-w64-mingw32/13.1.0/include/stdint.h:9,
                 from D:/msys64/home/User/KHDays_FM/src/types.h:22,
                 from D:/msys64/home/User/KHDays_FM/src/dolphin/BitSet.h:8,
                 from D:/msys64/home/User/KHDays_FM/src/dolphin/x64Emitter.h:16,
                 from D:/msys64/home/User/KHDays_FM/src/ARMJIT_x64/ARMJIT_Compiler.h:22,
                 from D:/msys64/home/User/KHDays_FM/src/ARMJIT_x64/ARMJIT_Branch.cpp:19:
D:/msys64/home/User/KHDays_FM/src/ARMJIT_x64/ARMJIT_Branch.cpp: In member function 'void ARMJIT::Co
mpiler::Comp_JumpTo(u32, bool)':
D:/msys64/home/User/KHDays_FM/src/ARMJIT_x64/ARMJIT_Branch.cpp:62:42: warning: 'offsetof' within no
n-standard-layout type 'ARMv5' is conditionally-supported [-Winvalid-offsetof]
   62 |             MOV(32, MDisp(RCPU, offsetof(ARMv5, RegionCodeCycles)), Imm32(regionCodeCycles))
;
      |                                          ^
D:/msys64/home/User/KHDays_FM/src/ARMJIT_x64/ARMJIT_Branch.cpp:109:42: warning: 'offsetof' within n
on-standard-layout type 'ARM' is conditionally-supported [-Winvalid-offsetof]
  109 |             MOV(32, MDisp(RCPU, offsetof(ARM, CodeRegion)), Imm32(codeRegion));
      |                                          ^
D:/msys64/home/User/KHDays_FM/src/ARMJIT_x64/ARMJIT_Branch.cpp:110:42: warning: 'offsetof' within n
on-standard-layout type 'ARM' is conditionally-supported [-Winvalid-offsetof]
  110 |             MOV(32, MDisp(RCPU, offsetof(ARM, CodeCycles)), Imm32(codeCycles));
      |                                          ^
D:/msys64/home/User/KHDays_FM/src/ARMJIT_x64/ARMJIT_Branch.cpp:144:38: warning: 'offsetof' within n
on-standard-layout type 'ARM' is conditionally-supported [-Winvalid-offsetof]
  144 |         MOV(32, MDisp(RCPU, offsetof(ARM, R[15])), Imm32(newPC));
      |                                      ^
D:/msys64/home/User/KHDays_FM/src/ARMJIT_x64/ARMJIT_Branch.cpp:148:38: warning: 'offsetof' within n
on-standard-layout type 'ARM' is conditionally-supported [-Winvalid-offsetof]
  148 |         ADD(32, MDisp(RCPU, offsetof(ARM, Cycles)), Imm8(cycles));
      |                                      ^
[57/138] Building CXX object src/CMakeFiles/core.dir/ARMJIT_x64/ARMJIT_Compiler.cpp.obj
In file included from D:/msys64/mingw64/lib/gcc/x86_64-w64-mingw32/13.1.0/include/stddef.h:1,
                 from D:/msys64/mingw64/include/stdint.h:32,
                 from D:/msys64/mingw64/lib/gcc/x86_64-w64-mingw32/13.1.0/include/stdint.h:9,
                 from D:/msys64/home/User/KHDays_FM/src/types.h:22,
                 from D:/msys64/home/User/KHDays_FM/src/dolphin/BitSet.h:8,
                 from D:/msys64/home/User/KHDays_FM/src/dolphin/x64Emitter.h:16,
                 from D:/msys64/home/User/KHDays_FM/src/ARMJIT_x64/ARMJIT_Compiler.h:22,
                 from D:/msys64/home/User/KHDays_FM/src/ARMJIT_x64/ARMJIT_Compiler.cpp:19:
D:/msys64/home/User/KHDays_FM/src/ARMJIT_x64/ARMJIT_Compiler.cpp: In constructor 'ARMJIT::Compiler:
:Compiler()':
D:/msys64/home/User/KHDays_FM/src/ARMJIT_x64/ARMJIT_Compiler.cpp:287:75: warning: 'offsetof' within
 non-standard-layout type 'ARM' is conditionally-supported [-Winvalid-offsetof]
  287 |         MOV(32, R(RSCRATCH3), MComplex(RCPU, RSCRATCH2, SCALE_4, offsetof(ARM, R_FIQ)));
      |                                                                           ^
D:/msys64/home/User/KHDays_FM/src/ARMJIT_x64/ARMJIT_Compiler.cpp:290:75: warning: 'offsetof' within
 non-standard-layout type 'ARM' is conditionally-supported [-Winvalid-offsetof]
  290 |         MOV(32, R(RSCRATCH3), MComplex(RCPU, RSCRATCH2, SCALE_4, offsetof(ARM, R_IRQ)));
      |                                                                           ^
D:/msys64/home/User/KHDays_FM/src/ARMJIT_x64/ARMJIT_Compiler.cpp:293:75: warning: 'offsetof' within
 non-standard-layout type 'ARM' is conditionally-supported [-Winvalid-offsetof]
  293 |         MOV(32, R(RSCRATCH3), MComplex(RCPU, RSCRATCH2, SCALE_4, offsetof(ARM, R_SVC)));
      |                                                                           ^
D:/msys64/home/User/KHDays_FM/src/ARMJIT_x64/ARMJIT_Compiler.cpp:296:75: warning: 'offsetof' within
 non-standard-layout type 'ARM' is conditionally-supported [-Winvalid-offsetof]
  296 |         MOV(32, R(RSCRATCH3), MComplex(RCPU, RSCRATCH2, SCALE_4, offsetof(ARM, R_ABT)));
      |                                                                           ^
D:/msys64/home/User/KHDays_FM/src/ARMJIT_x64/ARMJIT_Compiler.cpp:299:75: warning: 'offsetof' within
 non-standard-layout type 'ARM' is conditionally-supported [-Winvalid-offsetof]
  299 |         MOV(32, R(RSCRATCH3), MComplex(RCPU, RSCRATCH2, SCALE_4, offsetof(ARM, R_UND)));
      |                                                                           ^
D:/msys64/home/User/KHDays_FM/src/ARMJIT_x64/ARMJIT_Compiler.cpp:329:61: warning: 'offsetof' within
 non-standard-layout type 'ARM' is conditionally-supported [-Winvalid-offsetof]
  329 |         MOV(32, MComplex(RCPU, RSCRATCH2, SCALE_4, offsetof(ARM, R_FIQ)), R(RSCRATCH3));
      |                                                             ^
D:/msys64/home/User/KHDays_FM/src/ARMJIT_x64/ARMJIT_Compiler.cpp:333:61: warning: 'offsetof' within
 non-standard-layout type 'ARM' is conditionally-supported [-Winvalid-offsetof]
  333 |         MOV(32, MComplex(RCPU, RSCRATCH2, SCALE_4, offsetof(ARM, R_IRQ)), R(RSCRATCH3));
      |                                                             ^
D:/msys64/home/User/KHDays_FM/src/ARMJIT_x64/ARMJIT_Compiler.cpp:337:61: warning: 'offsetof' within
 non-standard-layout type 'ARM' is conditionally-supported [-Winvalid-offsetof]
  337 |         MOV(32, MComplex(RCPU, RSCRATCH2, SCALE_4, offsetof(ARM, R_SVC)), R(RSCRATCH3));
      |                                                             ^
D:/msys64/home/User/KHDays_FM/src/ARMJIT_x64/ARMJIT_Compiler.cpp:341:61: warning: 'offsetof' within
 non-standard-layout type 'ARM' is conditionally-supported [-Winvalid-offsetof]
  341 |         MOV(32, MComplex(RCPU, RSCRATCH2, SCALE_4, offsetof(ARM, R_ABT)), R(RSCRATCH3));
      |                                                             ^
D:/msys64/home/User/KHDays_FM/src/ARMJIT_x64/ARMJIT_Compiler.cpp:345:61: warning: 'offsetof' within
 non-standard-layout type 'ARM' is conditionally-supported [-Winvalid-offsetof]
  345 |         MOV(32, MComplex(RCPU, RSCRATCH2, SCALE_4, offsetof(ARM, R_UND)), R(RSCRATCH3));
      |                                                             ^
D:/msys64/home/User/KHDays_FM/src/ARMJIT_x64/ARMJIT_Compiler.cpp: In member function 'void ARMJIT::
Compiler::LoadCPSR()':
D:/msys64/home/User/KHDays_FM/src/ARMJIT_x64/ARMJIT_Compiler.cpp:479:44: warning: 'offsetof' within
 non-standard-layout type 'ARM' is conditionally-supported [-Winvalid-offsetof]
  479 |     MOV(32, R(RCPSR), MDisp(RCPU, offsetof(ARM, CPSR)));
      |                                            ^
D:/msys64/home/User/KHDays_FM/src/ARMJIT_x64/ARMJIT_Compiler.cpp: In member function 'void ARMJIT::
Compiler::SaveCPSR(bool)':
D:/msys64/home/User/KHDays_FM/src/ARMJIT_x64/ARMJIT_Compiler.cpp:486:38: warning: 'offsetof' within
 non-standard-layout type 'ARM' is conditionally-supported [-Winvalid-offsetof]
  486 |         MOV(32, MDisp(RCPU, offsetof(ARM, CPSR)), R(RCPSR));
      |                                      ^
D:/msys64/home/User/KHDays_FM/src/ARMJIT_x64/ARMJIT_Compiler.cpp: In member function 'void ARMJIT::
Compiler::LoadReg(int, Gen::X64Reg)':
D:/msys64/home/User/KHDays_FM/src/ARMJIT_x64/ARMJIT_Compiler.cpp:495:52: warning: 'offsetof' within
 non-standard-layout type 'ARM' is conditionally-supported [-Winvalid-offsetof]
  495 |         MOV(32, R(nativeReg), MDisp(RCPU, offsetof(ARM, R) + reg*4));
      |                                                    ^
D:/msys64/home/User/KHDays_FM/src/ARMJIT_x64/ARMJIT_Compiler.cpp: In member function 'void ARMJIT::
Compiler::SaveReg(int, Gen::X64Reg)':
D:/msys64/home/User/KHDays_FM/src/ARMJIT_x64/ARMJIT_Compiler.cpp:502:34: warning: 'offsetof' within
 non-standard-layout type 'ARM' is conditionally-supported [-Winvalid-offsetof]
  502 |     MOV(32, MDisp(RCPU, offsetof(ARM, R) + reg*4), R(nativeReg));
      |                                  ^
D:/msys64/home/User/KHDays_FM/src/ARMJIT_x64/ARMJIT_Compiler.cpp: In member function 'void ARMJIT::
Compiler::Comp_SpecialBranchBehaviour(bool)':
D:/msys64/home/User/KHDays_FM/src/ARMJIT_x64/ARMJIT_Compiler.cpp:675:36: warning: 'offsetof' within
 non-standard-layout type 'ARM' is conditionally-supported [-Winvalid-offsetof]
  675 |         OR(8, MDisp(RCPU, offsetof(ARM, IdleLoop)), Imm8(0x1));
      |                                    ^
D:/msys64/home/User/KHDays_FM/src/ARMJIT_x64/ARMJIT_Compiler.cpp:683:42: warning: 'offsetof' within
 non-standard-layout type 'ARM' is conditionally-supported [-Winvalid-offsetof]
  683 |             ADD(32, MDisp(RCPU, offsetof(ARM, Cycles)), Imm32(ConstantCycles));
      |                                          ^
D:/msys64/home/User/KHDays_FM/src/ARMJIT_x64/ARMJIT_Compiler.cpp: In member function 'void (* ARMJI
T::Compiler::CompileBlock(ARM*, bool, ARMJIT::FetchedInstr*, int, bool))()':
D:/msys64/home/User/KHDays_FM/src/ARMJIT_x64/ARMJIT_Compiler.cpp:750:42: warning: 'offsetof' within
 non-standard-layout type 'ARM' is conditionally-supported [-Winvalid-offsetof]
  750 |             MOV(32, MDisp(RCPU, offsetof(ARM, R[15])), Imm32(R15));
      |                                          ^
D:/msys64/home/User/KHDays_FM/src/ARMJIT_x64/ARMJIT_Compiler.cpp:753:46: warning: 'offsetof' within
 non-standard-layout type 'ARM' is conditionally-supported [-Winvalid-offsetof]
  753 |                 MOV(32, MDisp(RCPU, offsetof(ARM, CodeCycles)), Imm32(CurInstr.CodeCycles));
      |                                              ^
D:/msys64/home/User/KHDays_FM/src/ARMJIT_x64/ARMJIT_Compiler.cpp:754:46: warning: 'offsetof' within
 non-standard-layout type 'ARM' is conditionally-supported [-Winvalid-offsetof]
  754 |                 MOV(32, MDisp(RCPU, offsetof(ARM, CurInstr)), Imm32(CurInstr.Instr));
      |                                              ^
D:/msys64/home/User/KHDays_FM/src/ARMJIT_x64/ARMJIT_Compiler.cpp:845:38: warning: 'offsetof' within
 non-standard-layout type 'ARM' is conditionally-supported [-Winvalid-offsetof]
  845 |         ADD(32, MDisp(RCPU, offsetof(ARM, Cycles)), Imm32(ConstantCycles));
      |                                      ^
D:/msys64/home/User/KHDays_FM/src/ARMJIT_x64/ARMJIT_Compiler.cpp: In member function 'void ARMJIT::
Compiler::Comp_AddCycles_C(bool)':
D:/msys64/home/User/KHDays_FM/src/ARMJIT_x64/ARMJIT_Compiler.cpp:868:38: warning: 'offsetof' within
 non-standard-layout type 'ARM' is conditionally-supported [-Winvalid-offsetof]
  868 |         ADD(32, MDisp(RCPU, offsetof(ARM, Cycles)), Imm8(cycles));
      |                                      ^
D:/msys64/home/User/KHDays_FM/src/ARMJIT_x64/ARMJIT_Compiler.cpp: In member function 'void ARMJIT::
Compiler::Comp_AddCycles_CI(u32)':
D:/msys64/home/User/KHDays_FM/src/ARMJIT_x64/ARMJIT_Compiler.cpp:880:38: warning: 'offsetof' within
 non-standard-layout type 'ARM' is conditionally-supported [-Winvalid-offsetof]
  880 |         ADD(32, MDisp(RCPU, offsetof(ARM, Cycles)), Imm8(cycles));
      |                                      ^
D:/msys64/home/User/KHDays_FM/src/ARMJIT_x64/ARMJIT_Compiler.cpp: In member function 'void ARMJIT::
Compiler::Comp_AddCycles_CI(Gen::X64Reg, int)':
D:/msys64/home/User/KHDays_FM/src/ARMJIT_x64/ARMJIT_Compiler.cpp:894:38: warning: 'offsetof' within
 non-standard-layout type 'ARM' is conditionally-supported [-Winvalid-offsetof]
  894 |         ADD(32, MDisp(RCPU, offsetof(ARM, Cycles)), R(RSCRATCH));
      |                                      ^
D:/msys64/home/User/KHDays_FM/src/ARMJIT_x64/ARMJIT_Compiler.cpp:899:38: warning: 'offsetof' within
 non-standard-layout type 'ARM' is conditionally-supported [-Winvalid-offsetof]
  899 |         ADD(32, MDisp(RCPU, offsetof(ARM, Cycles)), R(i));
      |                                      ^
D:/msys64/home/User/KHDays_FM/src/ARMJIT_x64/ARMJIT_Compiler.cpp: In member function 'void ARMJIT::
Compiler::Comp_AddCycles_CDI()':
D:/msys64/home/User/KHDays_FM/src/ARMJIT_x64/ARMJIT_Compiler.cpp:937:42: warning: 'offsetof' within
 non-standard-layout type 'ARM' is conditionally-supported [-Winvalid-offsetof]
  937 |             ADD(32, MDisp(RCPU, offsetof(ARM, Cycles)), Imm8(cycles));
      |                                          ^
D:/msys64/home/User/KHDays_FM/src/ARMJIT_x64/ARMJIT_Compiler.cpp: In member function 'void ARMJIT::
Compiler::Comp_AddCycles_CD()':
D:/msys64/home/User/KHDays_FM/src/ARMJIT_x64/ARMJIT_Compiler.cpp:981:38: warning: 'offsetof' within
 non-standard-layout type 'ARM' is conditionally-supported [-Winvalid-offsetof]
  981 |         ADD(32, MDisp(RCPU, offsetof(ARM, Cycles)), Imm8(cycles));
      |                                      ^
[59/138] Building CXX object src/CMakeFiles/core.dir/ARMJIT.cpp.obj
In file included from D:/msys64/mingw64/include/stdint.h:32,
                 from D:/msys64/mingw64/lib/gcc/x86_64-w64-mingw32/13.1.0/include/stdint.h:9,
                 from D:/msys64/home/User/KHDays_FM/src/types.h:22,
                 from D:/msys64/home/User/KHDays_FM/src/ARMJIT.h:22,
                 from D:/msys64/home/User/KHDays_FM/src/ARMJIT.cpp:19:
D:/msys64/home/User/KHDays_FM/src/ARMJIT.cpp:51:24: warning: 'offsetof' within non-standard-layout
type 'ARM' is conditionally-supported [-Winvalid-offsetof]
   51 | static_assert(offsetof(ARM, CPSR) == ARM_CPSR_offset, "");
      |                        ^
D:/msys64/home/User/KHDays_FM/src/ARMJIT.cpp:52:24: warning: 'offsetof' within non-standard-layout
type 'ARM' is conditionally-supported [-Winvalid-offsetof]
   52 | static_assert(offsetof(ARM, Cycles) == ARM_Cycles_offset, "");
      |                        ^
D:/msys64/home/User/KHDays_FM/src/ARMJIT.cpp:53:24: warning: 'offsetof' within non-standard-layout
type 'ARM' is conditionally-supported [-Winvalid-offsetof]
   53 | static_assert(offsetof(ARM, StopExecution) == ARM_StopExecution_offset, "");
      |                        ^
ninja: build stopped: subcommand failed.

**Comment by vitor251093** [comment]
This seems to be the real issue:

> D:/msys64/home/User/KHDays_FM/src/GPU3D_TexcacheOpenGL.cpp:30:38: error: cannot convert 'const std:
:filesystem::__cxx11::path::value_type*' {aka 'const wchar_t*'} to 'const char*' in initialization
30 | const char* path = fullPath.c_str();

That doesn't give any issues in my computer, but it may be due to a different version of C++, or something like that. Let me create a pull request to master. That will be enough to trigger a GitHub build, and it may give us some light.

**Comment by sandwichwater** [comment]
huh , seems to give an error here too , with the same "FAILED: src/CMakeFiles/core.dir/GPU3D_TexcacheOpenGL.cpp.obj" message too

**Comment by vitor251093** [comment]
Indeed. For some confusing reason, that casting works on Linux, but not on Windows. I'm gonna need to investigate it further

**Comment by vitor251093** [comment]
I just discovered that the alpha value in those images is 31, while the usual max for a PNG is 255.

I thought "maybe the NDS only supports an alpha value between 0 and 31 (5 bits) instead of the usual 0 to 255 (8 bits)?", and tried ccomparing the bits of the exported images when compared to screenshots of the game.

Turns out that was the case. R, G and B have 6 bits, while alpha has 5 bits.

I've made the adjusts manually, while loading and exporting, and that was the result:

![Untitled](https://github.com/vitor251093/KHDays_FM/assets/8976483/0f8e6b7a-ca77-404d-b513-795c951683fe)

So, yeah... I think we can now try to replace the textures with new ones.

**Comment by sandwichwater** [comment]
thats great news , is the windows version still bugged ¿

**Comment by vitor251093** [comment]
The last Windows did work, so it should be fixed by now.

During my tests, I've managed to edit textures and see the changes reflected ingame (like turning the small crown in the intro red), but I've only managed to replace textures from the intro if they have the exact same size. If the size is different, it doesn't work.

It might be related with the shader, but I'm not sure.

**Comment by vitor251093** [comment]
I also didn't manage to extract textures from 2D scenes yet. Only from 3D ones.

Because of that, the only textures I had acccess to from the intro were the ones from the game logo animation.

**Comment by vitor251093** [comment]
> The last Windows build did complete, so it should be fixed by now.

Nevermind that. The method was broken. I still need to fix it

**Comment by sandwichwater** [comment]
ah no worries , best to have it functional without the texture limit than to rush it , its super exciting either way

**Comment by vitor251093** [comment]
Good news: I managed to replace textures with new ones with different resolutions. As far as I can say, any size should work.

Although, I'm having problems with some transparency levels. I think the logic behind the transparency values may be more complicated then what I originally presumed.

Still, the ingame textures that are loaded in 3D scenes can already be replaced with new ones. At first I was trying to replace the images from the intro, but those are hard to take a good screenshot to show, so I will replace part of the ingame HUD.

**Comment by sandwichwater** [comment]
that is huge news , thats honestly really exciting , though im guessing the windows build is still having issues ¿

**Comment by vitor251093** [comment]
My last commit may fix the Windows issue, but I won't be able to test it myself.

Create a folder called "textures" in the project folder (alongside the README.md file), and it should work normally.

Regarding the texture replacement, unfortunately my fix doesn't seem to work on every single situation. Some textures are replaceable with textures with a bigger size (like the intro textures) and some are not (like the counter on the top left of the screen, while doing a mission).

I suppose this depends on the kind of texture, but still, it's just a matter of time until we can figure out how to cover all the scenarios.

**Comment by vitor251093** [comment]
The game intro, with high resolution crown and high resolution "Kingdom Hearts", but with poor transparency detection.

![2023-06-20_02-50_4](https://github.com/vitor251093/KHDays_FM/assets/8976483/df35ed4e-b14f-4458-a6e5-9fd8edaee8f0)

**Comment by sandwichwater** [comment]
so , it does work (yippee) , though replaced textures dont seem to be correctly placed , for example if i edit one texture itll get replaced , just with another texture in the folder

**Comment by sandwichwater** [comment]
> for example if i edit one texture itll get replaced , just with another texture in the folder , and seems to get randomized every time the scene is reloaded as well

did a bit of testing and it seems like its because its because every texture is assigned a different hash each time the texture//game is loaded , ive edited the kingdom key texture three times now with three different hashes and every time i reload the game the ds res texture gets dumped with a completely different hash as the others . this is also why other custom textures are randomized , for example the kingdom key texture is assigned to roxas hair textures
![Screenshot (241)](https://github.com/vitor251093/KHDays_FM/assets/70611518/e37a6c1b-0236-4c6c-a5ec-1af527532174)

**Comment by vitor251093** [comment]
> also doesnt seem like 2d elements get dumped yet , just 3d ones or ones that are in a 3d space (panels , menu logo , models , heart points , days counter , off the top of my head)

Yup, this is what I was refering to before when I said "I also didn't manage to extract textures from 2D scenes yet. Only from 3D ones.". That didn't change unfortunately.

> did a bit of testing and it seems like its because its because every texture is assigned a different hash each time the texture//game is loaded

Yeah, I guess using the "key" value as the identifier wasn't the best idea. I just replaced it with a hash of the bytes of the original texture, so that may be fine grained enough.

> also experiencing some crashes when trying to load textures , i almost guessed it was memory issues but that doesnt seem to be the case as i replaced the kingdom key texture just fine with no crashes . whatever the case is , its still a work in progress so its understandable

Weird. That's an issue I didn't face. Was there any specific texture that caused that?

**Comment by sandwichwater** [comment]
> Yup, this is what I was refering to before when I said "I also didn't manage to extract textures from 2D scenes yet. Only from 3D ones."

ohhh i understand now , thought you meant for just the 2d cutscenes , my apologies then


> Was there any specific texture that caused that?

nope , happened for most of the textures i replaced , on the off chance it did actually load it didnt load the correct texture

**Comment by vitor251093** [comment]
The latest build should be more stable regarding texture replacement. Also, I managed to replace textures from 3D scenarios, like keyblades, even with different sizes.

I still didn't solve the alpha bug though. That will be my priority right now.

**Comment by vitor251093** [comment]
Alpha channel bug fixed. I was calculating the 5-bit value of alpha like this: (alpha + 1 >> 3) - 1

But it turns out this causes an integer overflow if the value is below 8. I honestly don't know why I made that calculation so complicated. Now it's like this: alpha >> 3

So with the exception of some UI elements, which seem to be cropped, the textures in 3D scenarios can be properly replaced now.

**Comment by vitor251093** [comment]
I've added both those images (the crown and the "Kingdom Hearts" logo) to the repository, so now anyone can reproduce this result.

I've also split the texture folder that is loaded by the game from the one where the exported textures are placed, so now it's easier to determine which textures are being overriden.

I've also added a placeholder file to the tmp folder, so the folder is automatically created.

**Comment by sandwichwater** [comment]
hmm ... still crashing after i add textures , if it makes any difference , theyre twilight town world textures

**Comment by vitor251093** [comment]
Well, I haven't tried to replace world textures yet, so I can't say for sure if I can replicate that issue. With that said...

![2023-06-20_17-32](https://github.com/vitor251093/KHDays_FM/assets/8976483/9198a036-f1a2-47fa-a52b-ee9a406e8529)

Who wants a remastered Kingdom Key?

**Comment by sandwichwater** [comment]
honestly remastered kingdom key was the first thing i did too😅 looks so natural and makes the texture look less flat as opposed to its native res texture

**Comment by vitor251093** [comment]
> actually , it seems like its just any world texture , i can replace model and item textures just fine , but when it comes to world textures the game just crashes if its over native res

Well, I did manage to replace the texture of a wall from the map above, but it was glitching.

Also, important warning: from what I can tell, both the image width and height MUST be multiples of two and two only, and they MUST be at least 8x8. So the width/height can only be 8, 16, 32, 64, 128, 256, 512 or 1024 (I also have my reasons to believe that a number bigger than 1024 may also failed, but honestly I didn't try).

**Comment by sandwichwater** [comment]
> from what I can tell, both the image width and height MUST be multiples of two (and two only), and they MUST be at least 8x8. So the width/height can only be 8, 16, 32, 64, 128, 256, 512 or 1024 (I also have my reasons to believe that a number bigger than 1024 may also fail, but honestly I didn't try).

thats good to know actually , ill have to check the dimensioms of the textures i was trying when i get home and see if it still causes crashes

**Comment by vitor251093** [comment]
A reminder for myself: the font used in the Day Counter scenes is very close to (if not the same as) Garamond Medium Extra Narrow Oblique.

https://www.myfonts.com/products/urw-garamond-t-medium-extra-narrow-oblique-garamond-333576

It should be easy to get high quality renderings of the numbers.

**Comment by vitor251093** [comment]
Done. The Day Counter now has high quality numbers.

**Comment by sandwichwater** [comment]
> > from what I can tell, both the image width and height MUST be multiples of two (and two only), and they MUST be at least 8x8. So the width/height can only be 8, 16, 32, 64, 128, 256, 512 or 1024 (I also have my reasons to believe that a number bigger than 1024 may also fail, but honestly I didn't try).
> 
> thats good to know actually , ill have to check the dimensioms of the textures i was trying when i get home and see if it still causes crashes

so im back and was able to test this , tried replacing a 32x32 texture with a 64x64 one and still crashes , very odd

**Comment by vitor251093** [comment]
Very weird indeed. Maybe it's a Windows only issue?

Does any of textures that I've included in the repo also cause a crash?

**Comment by sandwichwater** [comment]
nope , which is even weirder , just seems to be environmental textures

**Comment by vitor251093** [comment]
I won't be able to make more progress today, but I will update this issue so it's specifically focused in textures from the DS 3D renderer, and create a new one for the textures being loaded by the 2D renderer, since the 3D ones no longer require a melonDS update.

**Comment by vitor251093** [comment]
> nope , which is even weirder , just seems to be environmental textures

Can you give me an example of a file that is causing that? If I can reproduce it, I may be able to fix it

**Comment by sandwichwater** [comment]
sure , these were the files i used ripped from kh2 :
![texture003](https://github.com/vitor251093/KHDays_FM/assets/70611518/7c04244e-d149-4e7a-9863-1115468f3072)
![texture023](https://github.com/vitor251093/KHDays_FM/assets/70611518/264d5d2e-f8a9-4e2e-96b1-b29afba73726)
![texture037](https://github.com/vitor251093/KHDays_FM/assets/70611518/0dcbe7a9-c792-46d1-adcc-7bd8c0c29e1e)
![texture007](https://github.com/vitor251093/KHDays_FM/assets/70611518/19c4ff99-ff7c-4368-8723-e8c2e7676c7d)
![texture008](https://github.com/vitor251093/KHDays_FM/assets/70611518/b19b9074-a431-4957-9fed-f1e5d3d5c84a)
![3823822310](https://github.com/vitor251093/KHDays_FM/assets/70611518/e162ba33-83da-4cc3-923c-d555014cf5d7)
![4069325116](https://github.com/vitor251093/KHDays_FM/assets/70611518/46d64a65-e4f1-4006-9a96-9ebf3e7aded9)


ive also encountered another issue when replacing gems , some sort of transparency issue ¿
![Screenshot (243)](https://github.com/vitor251093/KHDays_FM/assets/70611518/e378428f-412b-4fb4-81f6-df24988d1b45)

even though transparency with munny and hp works just fine
![image](https://github.com/vitor251093/KHDays_FM/assets/70611518/906e05e1-c413-4822-9eeb-197a1fedeb09)

**Comment by vitor251093** [comment]
It tried replacing the welcome poster, but first made a comparison with the ingame texture.

I'm not sure if that was the cause of the error, but by simple leaving the orange block untouched, the poster was properly recognized.

![2023-06-21_16-44](https://github.com/vitor251093/KHDays_FM/assets/8976483/6331efc7-b351-4c19-aeec-98fbddb23665)

Although, for some reason, that caused some issue with the heart on the top left corner.

**Comment by sandwichwater** [comment]
interesting , i just tried it again and youre right it does work . mustve just assumed it didnt work as i did try it in a group of others , did the other textures give any issue ¿

> Although, for some reason, that caused some issue with the heart on the top left corner.

ive noticed this happens too based on where youre looking oddly enough , i can upload a video showing what exactly is happening too

**Comment by vitor251093** [comment]
> did the other textures give any issue ¿

I didn't try any of the others yet. That grass is from the secret passage in Twilight Town, right?

**Comment by sandwichwater** [comment]
> That grass is from the secret passage in Twilight Town, right?

yep , and the forest and mansion areas

**Comment by vitor251093** [comment]
With this one, I could reproduce the crash. Analysing that scenario.

**Comment by sandwichwater** [comment]
> also experiencing some crashes when trying to load textures , i almost guessed it was memory issues but that doesnt seem to be the case as i replaced the kingdom key texture just fine with no crashes

i think i discovered the issue , for some reason , textures _need_ to have atleast some transparency in order to work , thats why the kingdom key , title menu , and poster worked , because they all have transparency . discovered this when i was creating a hi res texture for one of luxords cards and accidentally made it way bigger than i needed to (the game stretched the texture ingame for some reason) but seemed to work when i scaled down the texture itself inside of the 512x512 area

**Comment by vitor251093** [comment]
You are correct. If I add a condition so it only handles the alpha calculations if there are 4 channels in the image file, it doesn't crash. Although, that made the game really glitchy.

![2023-06-22_11-58](https://github.com/vitor251093/KHDays_FM/assets/8976483/85548425-8db3-44e4-8017-0063e208f4b4)

I think this happens because the game expects an image whose bytes include the alpha channel, and in that case it doesn't. I should be able to fix that if I include the alpha channel myself if it's not present. I will try that.

**Comment by vitor251093** [comment]
Textures without an alpha channel now should be loaded properly.

![2023-06-22_12-13](https://github.com/vitor251093/KHDays_FM/assets/8976483/8375d444-4576-46fc-85df-4918340d3a45)

**Comment by vitor251093** [comment]
The bug involving the heart counter seems to also happen when the grass texture is on screen.

If my theory about the same size is correct, maybe we can avoid the issue if the textures are scaled proportionally? Like, 4x the original size? Idk, just theorizing. I need to do more tests

**Comment by vitor251093** [comment]
Curiously enough, if I resize the heart from 256x256 to 64x64, it becomes stuck with just a fragment of the image appearing, but it gets stable. This may be connected with the behaviour of the textures from the numbers next to it, which were also cropped in my prior tests.

**Comment by sandwichwater** [comment]
if it helps any with figuring out the problem , other textures seem to resize based on the texures depending on where youre looking too :


https://github.com/vitor251093/KHDays_FM/assets/70611518/f23b2c1d-941b-4243-a177-81d9b553ea0b

**Comment by vitor251093** [comment]
Uhnnn, so other textures are affected as well. That's good to know. It's not something affecting this specific texture then.

Also, fixing it will probably fix the issue with the numbers as well.

**Comment by sandwichwater** [comment]
> ive also encountered another issue when replacing gems , some sort of transparency issue ¿
> ![Screenshot (243)](https://user-images.githubusercontent.com/70611518/247380520-e378428f-412b-4fb4-81f6-df24988d1b45.png)

so , apparently this doesnt just apply to gems , just that certain levels of transparency simply dont show up , on any texture

**Comment by vitor251093** [comment]
Well, the DS only seems to support 5 bits of transparency, so the 3 rightmost bits of transparency are ignored. But maybe it goes beyond that then?

**Comment by sandwichwater** [comment]
worth a shot , as there are a good bit of textures that turn completely transparent currently

**Comment by vitor251093** [comment]
> and this project does well beyond what the ds was originally capable of

While this is true, the shaders are still based in the DS textures, which have that limitation. The shaders would need to be updated in order to support textures of a higher quality.

**Comment by sandwichwater** [comment]
hey , quick question , would it be possible to port the texture replacement function of the compute shaders to the normal opengl renderer ¿ the compute shader renderer is proving to have a lot of graphical issues that make having hd textures troublesome . i have a good bit of world textures finished , about 90% of twilight town and some of twtnw , but id rather wait to add them until all the issues are sorted out so users dont have to deal with graphical issues

**Comment by vitor251093** [comment]
It isn't possible unfortunately. At least not with ease. The texture replacement function requires the workflow to have texture caching, and that's not a thing in the normal opengl renderer.

**Comment by sandwichwater** [comment]
all good👍 was just wondering , i guess we just have to hope the melonds team fixes the issues on their end
