### ISSUE TITLE
Roxas Thoughts and Day Counter bugs

### ISSUE THREAD

**Issue by sandwichwater** [vitor251093/KHDays_FM#70]
roxas thoughts dont seem to show up , they can still be progressed as heard by the sounds still playing but nothing shows up . in addition to this , single digit days display in dual screen mode , the issue seems to resolve past day 10 . double and triple digit days all display correctly

https://github.com/vitor251093/KHDays_FM/assets/70611518/adb70422-9cde-46c5-9a65-1b8b7fd7e0ad

**Comment by vitor251093** [comment]
Fixed both the Roxas thoughts and the 1 digit Day Counter issue

**Comment by sandwichwater** [comment]
youre gonna hate to hear this ... but this bug is back lmao😅 it might be related to other similar issues happening but i cant tell for sure

**Comment by vitor251093** [comment]
It's probably the credits bug fix (#79) which caused this. I think there are instances of both Roxas Thoughts and Day Counters which are confused as cutscenes, and cutscenes with black backgrounds are being considered as credits. I will revert the credits fix in order to keep this working for now
